---
Name: cdnservices
---
Injector:
  ThemeCdn:
    properties:
      contentDelivery: %$ContentDeliveryService
      contentService: %$ContentService
  CdnControllerExtension:
    properties:
      contentDelivery: %$ContentDeliveryService
      contentService: %$ContentService
      contentFilter: %$AssetUrlFilter
  AssetUrlFilter:
    class: AssetUrlConversionFilter
  RequestProcessor:
    properties:
      filters: 
        - %$AssetUrlFilter
---
name: extensions
---
Image_Cached:
  extensions:
    - SilverStripeAustralia\ContentServiceAssets\ImageCachedExtension
CdnImage_Cached:
  extensions:
    - SilverStripeAustralia\ContentServiceAssets\ImageCachedExtension
Controller:
  extensions:
    - CdnControllerExtension
HtmlEditorField:
  extensions:
    - HtmlEditorExtension
DatabaseAdmin:
  extensions:
    - DevBuildExtension
#
#Upload:
#  extensions:
#    - SilverStripeAustralia\ContentServiceAssets\UploadExtension

---
name: injector
---
Injector:
  SilverStripeAustralia\ContentServiceAssets\ImageBackend:
    factory: SilverStripeAustralia\ContentServiceAssets\ImageBackendFactory
  SilverStripeAustralia\ContentServiceAssets\ImageBackendFactory:
    constructor:
      - "GDBackend"
  SilverStripeAustralia\ContentServiceAssets\ImageCachedExtension:
    constructor:
      - %$ContentService
  SilverStripeAustralia\ContentServiceAssets\VersionedFileExtension:
    constructor:
      - %$ContentService
---
name: versioned_files
only:
  moduleexists: versionedfiles
---
FileVersion:
  extensions:
    - SilverStripeAustralia\ContentServiceAssets\VersionedFileExtension

---
Name: cdn_image_settings
---
File:
  class_for_file_extension: 
    jpg: CdnImage
    jpeg: CdnImage
    png: CdnImage
    gif: CdnImage
    bmp: CdnImage
Injector:
  Image:
    class: CdnImage

---
Name: cdn_routes
After: '#secureassetsroutes'
---
Director:
  rules:
    'cdnassets': 'CDNSecureFileController'
    'assets': 'CDNSecureFileController'
